### ISSUE TITLE
Add support for undocumented API endpoints

### ISSUE THREAD

**Issue by KyleKotowick** [palanik/slack-php#3]
Is there any chance of adding support for undocumented API endpoints? For example, I'd like to use the "channel.delete" endpoint, but can't do so using this library.

Details: https://github.com/ErikKalkoken/slackApiDoc

If you don't want to add these endpoints to your library because they might change, is there any other way to call them?

**Comment by palanik** [comment]
Interesting....

`slack-php` is built on top of [`wrapi`](https://packagist.org/packages/palanik/wrapi), a generic library to wrap restful API endpoints.

 `wrapi` allows adding additional individual endpoints via the `register` method. 

For example, to add `channels.delete` method
$slack = new wrapi\slack\slack(SLACK_API_TOKEN);

**Comment by palanik** [comment]
Interesting....

`slack-php` is built on top of [`wrapi`](https://packagist.org/packages/palanik/wrapi), a generic library to wrap restful API endpoints.

 `wrapi` allows adding more individual endpoints. 

For example, to add `channels.delete` method
```
$slack = new wrapi\slack\slack(SLACK_API_TOKEN);
$slack("channels.delete",
  array(
    "method" => "GET",
    "path" => "channels.delete"
  )
);
```

HTH
