### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by arunwebber** [palanik/slack-php#6]
For example, if I use like this in my PHP project it is showing me an error
require_once('slack/src/slack.php');

Class 'wrapi\\wrapi' not found

**Comment by palanik** [comment]
You need to install dependent libraries.

Install from [packagist](https://packagist.org/packages/wrapi/slack) using the [composer](https://getcomposer.org/composer.phar) package manager.

`composer require wrapi/slack`

This will install all the dependent libraries along with wrapi/slack.

More info: https://getcomposer.org/doc/01-basic-usage.md


To use:
```php
$slack = new wrapi\slack\slack(SLACK_API_TOKEN);

$slack->chat->postMessage(array(
    "channel" => "#general",
    "text" => "Hello World!"
  )
);
```

**Comment by arunwebber** [comment]
Yeah the problem is solved.
Thank you a good API also do let me know how can I add a message like this.

`Title`
`A hyper link`
`Some paragraph`

**Comment by palanik** [comment]
Formatted messages like the ones you specified are sent as attachments in the `postMessage` call..

Please refer to Slack API on formatting messages.
https://api.slack.com/docs/message-formatting
