### ISSUE TITLE
Slack: Deprecating usage of token as a query string parameter in Web API requests

### ISSUE THREAD

**Issue by aaronpollock** [palanik/slack-php#9]
I noticed recently using your library it no longer will work on newly created Slack apps, likely because of this change:
https://api.slack.com/changelog/2020-11-no-more-tokens-in-querystrings-for-newly-created-apps

Because of this change, no matter the query, the response will always be:

```
Array
(
    [ok] =>
    [error] => invalid_auth
)
```

My incredibly lazy workaround is to modify slack.php and add a "Authorization" header with content of "Bearer ".$token, but I assume there is a better way. Just giving you a heads up!

**Comment by palanik** [comment]
Thanks for bringing this to my attention. 
I will take a look.

**Comment by palanik** [comment]
Updated and published the code changes for using the `Authorization` header.
@aaronpollock Please check.

Thanks
